import Foundation

/// Stores guest user preferences in memory (not persisted to database)
/// Used when users browse without signing in
@MainActor
class GuestPreferencesStore: ObservableObject {
    static let shared = GuestPreferencesStore()

    // MARK: - Search Preferences (from onboarding)
    @Published var areaName: String = ""
    @Published var latitude: Double?
    @Published var longitude: Double?
    @Published var radius: Double = 1.0
    @Published var minBedrooms: Int?
    @Published var maxBedrooms: Int?
    @Published var minBathrooms: Int?
    @Published var maxBathrooms: Int?
    @Published var minPrice: Int?
    @Published var maxPrice: Int?
    @Published var furnishType: String?

    // MARK: - Properties (fetched during onboarding)
    @Published var properties: [Property] = []

    // MARK: - Computed Properties

    var hasValidPreferences: Bool {
        latitude != nil && longitude != nil && !areaName.isEmpty
    }

    /// Creates a SearchQuery from the stored preferences (for API calls)
    func toSearchQuery() -> SearchQuery? {
        guard let lat = latitude, let lng = longitude else { return nil }

        return SearchQuery(
            name: autoGeneratedName,
            areaName: areaName,
            latitude: lat,
            longitude: lng,
            minPrice: minPrice,
            maxPrice: maxPrice,
            minBedrooms: minBedrooms,
            maxBedrooms: maxBedrooms,
            minBathrooms: minBathrooms,
            maxBathrooms: maxBathrooms,
            radius: radius,
            furnishType: furnishType
        )
    }

    private var autoGeneratedName: String {
        var parts: [String] = []

        let shortArea = areaName.split(separator: ",").first.map(String.init) ?? areaName
        if !shortArea.isEmpty {
            parts.append(shortArea)
        }

        if let min = minBedrooms, let max = maxBedrooms, min == max {
            parts.append(min == 0 ? "Studio" : "\(min)-bed")
        } else if let min = minBedrooms {
            parts.append(min == 0 ? "Studio" : "\(min)+ bed")
        } else if let max = maxBedrooms {
            parts.append("Up to \(max)-bed")
        }

        return parts.isEmpty ? "My Search" : parts.joined(separator: " ")
    }

    // MARK: - Methods

    func clear() {
        areaName = ""
        latitude = nil
        longitude = nil
        radius = 1.0
        minBedrooms = nil
        maxBedrooms = nil
        minBathrooms = nil
        maxBathrooms = nil
        minPrice = nil
        maxPrice = nil
        furnishType = nil
        properties = []
    }

    func setFromOnboarding(
        areaName: String,
        latitude: Double,
        longitude: Double,
        radius: Double,
        minBedrooms: Int?,
        maxBedrooms: Int?,
        minBathrooms: Int?,
        maxBathrooms: Int?,
        minPrice: Int?,
        maxPrice: Int?,
        furnishType: String?
    ) {
        self.areaName = areaName
        self.latitude = latitude
        self.longitude = longitude
        self.radius = radius
        self.minBedrooms = minBedrooms
        self.maxBedrooms = maxBedrooms
        self.minBathrooms = minBathrooms
        self.maxBathrooms = maxBathrooms
        self.minPrice = minPrice
        self.maxPrice = maxPrice
        self.furnishType = furnishType
    }
}
