name: Monitor User Properties

on:
  # Allow manual trigger with user_id input
  workflow_dispatch:
    inputs:
      user_id:
        description: 'User ID to run monitor for'
        required: true
        type: string

  # Webhook trigger from iOS app
  repository_dispatch:
    types: [monitor-user]

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run property monitor for user
      working-directory: ./backend
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        APN_AUTH_KEY: ${{ secrets.APN_AUTH_KEY }}
        APN_KEY_ID: ${{ secrets.APN_KEY_ID }}
        APN_TEAM_ID: ${{ secrets.APN_TEAM_ID }}
        APN_BUNDLE_ID: ${{ secrets.APN_BUNDLE_ID }}
      run: |
        USER_ID="${{ github.event.inputs.user_id || github.event.client_payload.user_id }}"
        echo "🔍 Running monitor for user: $USER_ID"
        npm run monitor "$USER_ID"
