name: Property Monitor

# Set permissions at workflow level
permissions:
  contents: write

on:
  schedule:
    # Run every hour to process all user queries from Supabase
    - cron: '0 * * * *'   # Every hour at the top of the hour
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  monitor_properties:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        working-directory: backend
        
      - name: Process all user queries from Supabase
        run: npm run monitor
        working-directory: backend
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
